language: php

services: mongodb


php:
  - 5.5
  - 5.6

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer self-update
  - composer install --no-interaction --dev

script:
  - bin/phpspec run -v