language: php

services:
  - mongodb

php:
  - 5.5
  - 5.6

before_script:
  - yes '' | pecl -q install -f mongo-1.2.12
  - composer self-update

install:
  - composer install --prefer-source --no-interaction --dev

script:
  - bin/phpspec run -v