language: php

services:
  - mongodb

before_script:
  - phpenv config-add php.ini
  - composer self-update

php:
  - 5.5
  - 5.6

install:
  - composer install --prefer-source --no-interaction --dev

script:
  - bin/phpspec run -v