imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to: "\.less$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                username: "%mongo_database_user%"
                password:  "%mongo_database_password%"
                db: "%mongo_database_db%"

    default_database: "%mongo_database_db%"
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost
braincrafted_bootstrap:
    less_filter: less

hwi_oauth:
    firewall_name: secured_area
    resource_owners:
        strava:
            type:                oauth2
            client_id:           %strava_id%
            client_secret:       %strava_secret%
            scope:              view_private
            access_token_url:    https://www.strava.com/oauth/token
            authorization_url:   https://www.strava.com/oauth/authorize
            infos_url:           https://www.strava.com/api/v3/athlete

            user_response_class: Century\CenturyBundle\Auth\Response\StravaPathResponse

            paths:
                identifier: id
                nickname: firstname
                realname: ['firstname', 'lastname']
                firstname: firstname
                lastname: lastname
                profilepicture: profile
                email: email
                city: city
                state: state
                country: country
                sex: sex
                measurement: measurement_preference
leezy_pheanstalk:
    enabled: true
    pheanstalks:
        primary:
            server: localhost
            default: true
