security:
    providers:
        oauth_provider:
            id: century.oauth_user_provider
    encoders:
        Century\CenturyBundle\Document\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
    firewalls:

        secured_area:
            anonymous: ~
            oauth:
                resource_owners:
                    strava:           "/login/check-strava"
                login_path:        /login
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: century.oauth_user_provider
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }