century_century_homepage:
    path:     /
    defaults: { _controller: CenturyCenturyBundle:Default:index }
century_century_rides:
    path:     /rides
    defaults: { _controller: CenturyCenturyBundle:Default:rides }
century_century_clubs:
    path:     /clubs
    defaults: { _controller: CenturyCenturyBundle:Default:clubs }
